ICAPortal/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ICAPortal.Controllers
{
    public class ChatController : Controller
    {
        public ActionResult LastChat()
        {
            return View();
        }
        // GET: Chat
        public ActionResult Pending()
        {
            return View();
        }
        public ActionResult History()
        {
            return View();
        }
    }
}

ICAPortal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ICAPortal.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            if (Session["Login"] == null)
            {
                return RedirectToAction("Login", "User");
            }

            return View();
        }
    }
}

ICAPortal/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ICAPortal.Controllers
{
    public class ListController : Controller
    {
        // GET: List
        public ActionResult StudentsList()
        {
            return View();
        }
        public ActionResult UniversityList()
        {
            return View();
        }
        public ActionResult ProfessorsList()
        {
            return View();
        }
    }
}

ICAPortal/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ICAPortal.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Login()
        {
            return View();
        }
       
        [HttpPost]
        public ActionResult Login(string uname, string pass)
        {
            if ((uname == "admin") && (pass == "admin"))
            {
                FormsAuthentication.SetAuthCookie(uname, true);
                Session["Login"] = "ADMIN";
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult Logout()
        {
            Session.RemoveAll();
            return RedirectToAction("Login", "User");
        }

    }
}

ICAPortal/Views/Chat/History.cshtml

@{
    ViewBag.Title = "History";
}

<h2>History</h2>


ICAPortal/Views/Chat/LastChat.cshtml

@{
    ViewBag.Title = "Last Chat";
}

<div ng-controller="lastchat" class="table-responsive" ng-show="waitdisplay">

    <div class="container">
        <div class="row groupheader" style="text-align:right">
            <div class="col-lg-7">
                <div class="col-lg-6">
                    <label class="text-left"> Select Course</label>
                </div>
                <div class="col-lg-6">
                    <select id="lchat_selected" name="lchat_selected" class="form-control dropdown" ng-model="lchat_groupId" ng-change="get_lchat_details()">
                        <option ng-repeat="icagroup in icagroups track by $index" value="{{$index}}"> {{icagroup}}</option>
                    </select>
                </div>
                <!-- <select ng-options="s.LessonName for s in icagroups" id="lchat_selected" name="lchat_selected" class="form-control dropdown" ng-model="lchat_group" ng-change="get_lchat_details()"></select>
         -->
            </div>
            <div class="col-lg-5">
                <input class="bottom-right" type="search" ng-model="searchKeyword" /> search
            </div>
            
        </div>
        <div class="row text-center text-danger">
            <span> {{processing}}</span>
        </div>
        <br />
        <div class="row">
            <div class="col-md-12" style="overflow-y:hidden">
                <table class="lastchattable  text-center" ng-hide="Displaychatlist">
                    <tr>
                        <th a href="" ng-click="orderByField='senderid'; reverseSort = !reverseSort">Sender Id</th>
                        <th a href="" ng-click="orderByField='receiverid'; reverseSort = !reverseSort">Receiver Id</th>
                        <th a href="" ng-click="orderByField='sendertype'; reverseSort = !reverseSort">Sender</th>
                        <th a href="" ng-click="orderByField='receiverType'; reverseSort = !reverseSort">Receiver</th>
                        <th a href="" ng-click="orderByField='date'; reverseSort = !reverseSort">Date</th>
                        <th a href="" ng-click="orderByField='message'; reverseSort = !reverseSort">Message</th>
                        <th a href="" ng-click="orderByField='NoOfDays'; reverseSort = !reverseSort">Days</th>
                    </tr>
                    <tr ng-repeat="lchatmessage in lchatmessages | filter: searchKeyword | orderBy:orderByField:reverseSort" ng-dblclick="getselectchathistory(lchatmessage)">
                        <td>{{lchatmessage.Senderid}}</td>
                        <td>{{lchatmessage.Receiverid}}</td>
                        <td>{{lchatmessage.SenderType}}</td>
                        <td>{{lchatmessage.ReceiverType}}</td>
                        <td>{{lchatmessage.Message_date | date }} {{lchatmessage.Message_date | date: 'hh:mm' }}</td>
                        <td>{{lchatmessage.Message}}</td>
                        <td>{{lchatmessage.NoOfDays}}</td>
                    </tr>
                </table>
                
                <div ng-hide="!Displaychatlist">
                    <div class="row chatheader">
                        <table class="chattable text-center">
                            <tr>
                                <th> </th>
                                <th>Id</th>
                                <th>Type </th>
                                <th>Name</th>
                                <th>Mobile</th>
                                <th>Email</th>
                                <th>Ping</th>
                            </tr>
                            <tr ng-show="is_Prof_Inst">
                                <!-- Id	Comment	StudentId	StudentName	StudentPhone	StudentPhone -->
                                <td></td>
                                <td>{{detailchat.StudentId}}</td>
                                <td>Student</td>
                                <td>{{detailchat.StudentName}}</td>
                                <td>{{detailchat.StudentPhone}}</td>
                                <td>{{detailchat.StudentEmail}}</td>
                                <td><input class="btn-group-vertical" type="button" value="Ping" ng-click="pinguser()" /></td>
                            </tr>

                            <tr>
                                <!-- SenderId	SenderName	SenderEmail	SenderPhone-->
                                <td>Sender</td>
                                <td>{{detailchat.SenderId}}</td>
                                <td>{{detailchat.SenderType}}</td>
                                <td>{{detailchat.SenderName}}</td>
                                <td>{{detailchat.SenderPhone}}</td>
                                <td>{{detailchat.SenderEmail}}</td>
                                <td><input class="btn-group-vertical" type="button" value="Ping" ng-click="pinguser()" /></td>
                            </tr>
                            <tr>
                                <!-- ReceiverId	ReceiverName	ReceiverEmail	ReceiverPhone	SenderId	SenderName	SenderEmail	SenderPhone-->
                                <td>Receiver</td>
                                <td>{{detailchat.ReceiverId}}</td>
                                <td>{{detailchat.ReceiverType}}</td>
                                <td>{{detailchat.ReceiverName}}</td>
                                <td>{{detailchat.ReceiverPhone}}</td>
                                <td>{{detailchat.ReceiverEmail}}</td>
                                <td><input class="btn-group-vertical" type="button" value="Ping" ng-click="pinguser()" /></td>
                            </tr>
                        </table>


                    </div>

                    <table class="chattable text-center">
                        <tr>
                            <th>Sender Id</th>
                            <th>Receiver Id</th>
                            <th>Sender</th>
                            <th>Receiver</th>
                            <th>Message</th>
                            <th>Date</th>
                            <th>Days</th>
                        </tr>
                        <tr ng-repeat="chatmessage in detailchat.ChatHistory">
                            <!-- | orderBy:chatmessage.Message_date | date: true "> -->
                            <td>{{chatmessage.Senderid}}</td>
                            <td>{{chatmessage.Receiverid}}</td>
                            <td>{{chatmessage.SenderType}}</td>
                            <td>{{chatmessage.ReceiverType}}</td>
                            <td>{{chatmessage.Message}}</td>
                            <td>{{chatmessage.Message_date | date}} {{chatmessage.Message_date | date: 'hh:mm'}}</td>
                            <td>{{chatmessage.NoOfDays}}</td>
                        </tr>
                    </table>
                    <br />
                    <input type="button" class="alert-link" value="Back to chat list" ng-click="set_displaychatlist()" />
                </div>

            </div>
        </div>
    </div>

    <!--     id senderid    receiverid sendertype  receiverType date    message senderid    receiverid lastvisiteddate     -->
    <br />

</div>

@section Scripts {
    @Scripts.Render("~/bundles/lastchat")
}

ICAPortal/Views/Chat/Pending.cshtml

@{
    ViewBag.Title = "Pending Chat";
}

 
<div ng-controller="pendingchat" class="table-responsive" ng-show="waitdisplay">
    
    <div class="container">
        <div class="row groupheader" style="text-align:right">
            <div class="col-lg-7">
                <div class="col-lg-6">
                    <label class="text-left"> Select Course</label>
                </div>
                <div class="col-lg-6">
                    <select id="pchat_selected" name="pchat_selected" class="form-control dropdown" ng-model="pchat_groupId" ng-change="get_pchat_details()">
                        <option ng-repeat="icagroup in icagroups track by $index" value="{{$index}}"> {{icagroup}}</option>
                    </select>
                </div>

                <!-- <select ng-options="s.LessonName for s in icagroups" id="pchat_selected" name="pchat_selected" class="form-control dropdown" ng-model="pchat_group" ng-change="get_pchat_details()"></select>
         -->

            </div>
            <div class="col-lg-5"  ng-hide="Displaychatlist" > 
            <input class="bottom-right" type="search" ng-model="searchKeyword" /> search</div>
            
        </div>
        <div class="row text-center text-danger">
            <span> {{processing}}</span>
        </div>
        <br/>
        <div class="row">
            <div class="col-md-12" style="overflow-y:hidden">
                <table class="pendchattable text-center" ng-hide="Displaychatlist" >
                    <tr >
                        <th a href="" ng-click="orderByField='senderid'; reverseSort = !reverseSort">Sender Id</th>
                        <th a href="" ng-click="orderByField='receiverid'; reverseSort = !reverseSort">Receiver Id</th>
                        <th a href="" ng-click="orderByField='sendertype'; reverseSort = !reverseSort">Sender</th>
                        <th a href="" ng-click="orderByField='receiverType'; reverseSort = !reverseSort">Receiver</th>
                        <th a href="" ng-click="orderByField='date'; reverseSort = !reverseSort">Date</th>
                        <th a href="" ng-click="orderByField='message'; reverseSort = !reverseSort">Message</th>
                        <th a href="" ng-click="orderByField='lastvisiteddate'; reverseSort = !reverseSort" >Last Visited</th>
                        <th a href="" ng-click="orderByField='NoOfDays'; reverseSort = !reverseSort">Days</th>
                    </tr>
                    <tr ng-repeat="pchatmessage in pchatmessages | filter: searchKeyword | orderBy:orderByField:reverseSort" ng-dblclick="getselectchathistory(pchatmessage)" >
                        <td>{{pchatmessage.Senderid}}</td>
                        <td>{{pchatmessage.Receiverid}}</td>
                        <td>{{pchatmessage.SenderType}}</td>
                        <td>{{pchatmessage.ReceiverType}}</td>
                        <td>{{pchatmessage.Message_date | date }} {{pchatmessage.Message_date | date: 'hh:mm' }}</td>
                        <td>{{pchatmessage.Message}}</td>
                        <td>{{pchatmessage.lastvisit | ICA_NullDate | date}} {{pchatmessage.lastvisit | ICA_NullDate | date : 'hh:mm'}}</td>
                        <td>{{pchatmessage.NoOfDays}}</td>
                    </tr>

                </table>
                <div ng-hide="!Displaychatlist">
                    <div class="row chatheader">
                        <table class="chattable text-center">
                            <tr>
                                <th> </th>
                                
                                <th>Id</th>
                                <th>Type </th>
                                <th>Name</th>
                                <th>Mobile</th>
                                <th>Email</th>
                                <th>Ping</th>
                            </tr>
                            <tr ng-show="is_Prof_Inst">
                                <!-- Id	Comment	StudentId	StudentName	StudentPhone	StudentPhone -->
                                <td></td>
                                <td>{{detailchat.StudentId}}</td>
                                <td>Student</td>
                                <td>{{detailchat.StudentName}}</td>
                                <td>{{detailchat.StudentPhone}}</td>
                                <td>{{detailchat.StudentEmail}}</td>
                                <td><input class="btn-group-vertical" type="button" value="Ping" ng-click="pinguser()" /></td>
                            </tr>
                          
                            <tr>
                                <!-- SenderId	SenderName	SenderEmail	SenderPhone-->
                                <td>Sender</td>
                                <td>{{detailchat.SenderId}}</td>
                                <td>{{detailchat.SenderType}}</td>
                                <td>{{detailchat.SenderName}}</td>
                                <td>{{detailchat.SenderPhone}}</td>
                                <td>{{detailchat.SenderEmail}}</td>
                                <td><input class="btn-group-vertical" type="button" value="Ping" ng-click = "pinguser()" /></td>
                            </tr>
                            <tr>
                                <!-- ReceiverId	ReceiverName	ReceiverEmail	ReceiverPhone	SenderId	SenderName	SenderEmail	SenderPhone-->
                                <td>Receiver</td>
                                <td>{{detailchat.ReceiverId}}</td>
                                <td>{{detailchat.ReceiverType}}</td>
                                <td>{{detailchat.ReceiverName}}</td>
                                <td>{{detailchat.ReceiverPhone}}</td>
                                <td>{{detailchat.ReceiverEmail}}</td>
                                <td><input class="btn-group-vertical" type="button" value="Ping" ng-click="pinguser()" /></td>
                            </tr>
                        </table>

                     
                    </div>
                    
                    <table class="chattable text-center" >
                        <tr>
                            <th>Sender Id</th>
                            <th>Receiver Id</th>
                            <th>Sender</th>
                            <th>Receiver</th>
                            <th>Message</th>
                            <th>Date</th>
                            <th>Days</th>
                        </tr>
                        <tr ng-repeat="chatmessage in detailchat.ChatHistory">
                            <!-- | orderBy:chatmessage.Message_date | date: true "> -->
                            <td>{{chatmessage.Senderid}}</td>
                            <td>{{chatmessage.Receiverid}}</td>
                            <td>{{chatmessage.SenderType}}</td>
                            <td>{{chatmessage.ReceiverType}}</td>
                            <td>{{chatmessage.Message}}</td>
                            <td>{{chatmessage.Message_date | date}} {{chatmessage.Message_date | date: 'hh:mm'}}</td>
                            <td>{{chatmessage.NoOfDays}}</td>
                        </tr>
                    </table>
                    <br />
                    <input type="button" class="alert-link" value="Back to chat list" ng-click="set_displaychatlist()" />
                    </div>
                </div>
        </div>
    </div>

    <div data-pagination="" data-num-pages="numPages()"
         data-current-page="currentPage" data-max-size="maxSize"
         data-boundary-links="true"></div>
    <!--     id senderid    receiverid sendertype  receiverType date    message senderid    receiverid lastvisiteddate
    ->
   
        -->
    <br />
    
</div>

@section Scripts {
    @Scripts.Render("~/bundles/pendingchat")
}

ICAPortal/Views/Home/Index.cshtml

@{
    ViewBag.Title = "Index";
}


<div ng-controller="dashboard" class="table-responsive" ng-show="waitdisplay">
    <div class="form-horizontal" ng-show="displaydashboard">

        <div class="col-md-4 dashboardbox">
            <div class="text-center">
                <label class="text-center" > Student Details</label>
            </div>
            <div class="row text-center text-danger">
                <span> {{processing}}</span>
            </div>
            <div class="col-sm-6">
                <label class="col-sm-6"><b>From</b></label>
                <input type="date" name="fromdate" ng-model="fromdate" max={{frommaxDate|date:'yyyy-MM-dd'}} >
                <br />
            </div>
            <div class="col-sm-6">
                <label class="col-sm-6"><b>To</b></label>
                <input type="date" name="todate" ng-model="todate"  max={{tomaxDate|date:'yyyy-MM-dd'}}>
            </div>

            <div class="text-right">
                <input type="submit" value="Submit" class="btn btn-default" ng-click="getstudentcounts()">
            </div>

            <div class="row">
                <br />
                <div class="col-xs-12">
                    <table class="lastchattable  text-center" ng-hide="Displaylist">
                        <tr>
                            <th a href="" ng-click="orderByField='Group'; reverseSort = !reverseSort">Group</th>
                            <th a href="" ng-click="orderByField='Count'; reverseSort = !reverseSort">Count</th>
                        </tr>
                        <tr ng-repeat="student in students | filter: searchKeyword | orderBy:orderByField:reverseSort" ng-dblclick="getselect(student, $index)">
                            <td>{{student.group}}</td>
                            <td>{{student.count}}</td>
                        </tr>
                    </table>
                </div>
            </div>


        </div>
  <br />
</div>

    <div class="row" ng-show="!displaydashboard">
        <div class="col-lg-5" >
            <input type="button" class="alert-link" value="Back to list" ng-click="backbuttonclick()" />     
           
        </div>
        <br />
        <div class="col-md-12" style="overflow-y:hidden">
            <table class="lastchattable  text-center" >
                <tr>
                    <!--  select id, name, gender, createdDate, emailaddress, phonenumber, collegeid, universityid from athelete                      -->
                    <th a href="" ng-click="orderByField='id'; reverseSort = !reverseSort">Id</th>
                    <th a href="" ng-click="orderByField='name'; reverseSort = !reverseSort">Name</th>
                    <th a href="" ng-click="orderByField='gender'; reverseSort = !reverseSort">Gender</th>
                    <th a href="" ng-click="orderByField='createdDate'; reverseSort = !reverseSort">Created</th>
                    <th a href="" ng-click="orderByField='emailaddress'; reverseSort = !reverseSort">Email</th>
                    <th a href="" ng-click="orderByField='phonenumber'; reverseSort = !reverseSort">Phone</th>
                    <th a href="" ng-click="orderByField='college'; reverseSort = !reverseSort">College</th>
                    <th a href="" ng-click="orderByField='university'; reverseSort = !reverseSort">University</th>
                </tr>
                <tr ng-repeat="student in studentsdetailslist | filter: searchKeyword | orderBy:orderByField:reverseSort" ng-dblclick="getselectstudent(student)">
                    <td>{{student.Id}}</td>
                    <td>{{student.Name}}</td>
                    <td>{{student.Gender}}</td>
                    <td>{{student.CreatedDate | date }} {{student.createdDate | date: 'hh:mm' }}</td>
                    <td>{{student.Emailaddress}}</td>
                    <td>{{student.Phonenumber}}</td>
                    <td>{{student.College}}</td>
                    <td>{{student.University}}</td>
                </tr>

            </table>

           
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/dashboard")
}

ICAPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ICA Portal</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body ng-app="icaportalmodule" >
    <div class="navbar navbar-inverse navbar-fixed-top navbar-ica">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("I C A Portal", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if ((Request.IsAuthenticated) || (Session["Login"] != null))
                {
                    <ul class="nav navbar-nav">
                        <!--       <li>@Html.ActionLink("Dashboard", "Index", "Home")</li> -->

                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Chat
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Last Chat", "LastChat", "Chat")</li>
                                <li>@Html.ActionLink("Pending", "Pending", "Chat")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                List
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Students", "StudentsList", "List")</li>
                                <li>@Html.ActionLink("University", "UniversityList", "List")</li>
                                <li>@Html.ActionLink("Professors", "ProfessorsList", "List")</li> 
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            @Html.ActionLink("Hello! " + User.Identity.Name + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                        </li>
                        <li>@Html.ActionLink("Log off", "Logout", "User") </li>
                    </ul>
                }
            </div>
        </div>
    </div>

    <div class="container body-content">
       
        <h2>@ViewBag.Title</h2>
        <fieldset class="for-panel">
            <legend>ICA Portal</legend>
            @RenderBody()


        </fieldset>
        <div>
            @Html.ActionLink("Back to Home", "Index", "home")
        </div>
        <footer>
            <p>&copy; @DateTime.Now.Year - ICA Portal</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ICAPortal/Views/User/Login.cshtml

@{
    ViewBag.Title = "Login";
}

<h5> Note: Enter admin admin </h5>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="form-group">
            <div class="col-md-10">
                <label class="control-label col-md-2"><b>Username</b></label>
                <input class="form-control" type="text" placeholder="Enter Username" name="uname" required>
                <br />
            </div>
            <div class="col-md-10">
                <label class="control-label col-md-2"><b>Password</b></label>
                <input class="form-control" type="password" placeholder="Enter Password" name="pass" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default">
                <span class="psw">Forgot <a href="#"> password?</a></span>
            </div>
        </div>
    </div>
}
